import { registerEnumType } from "@nestjs/graphql";

export enum EventType {
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILED = 'LOGIN_FAILED',
    LOGOFF = 'LOGOFF',
    DATA_CHANGE = 'DATA_CHANGE',
    POLICY_CHANGE = 'POLICY_CHANGE',
    PASSWORD_CHANGE = 'PASSWORD_CHANGE',
    LOG_CHANGE_ATTEMPT = 'LOG_CHANGE_ATTEMPT',
    ACCOUNT_ENABLED = 'ACCOUNT_ENABLED',
    ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
    ACCOUNT_CREATED = 'ACCOUNT_CREATED',
    ACCOUNT_DELETED = 'ACCOUNT_DELETED',
    ACCOUNT_PERMISSION_CHANGE = 'ACCOUNT_PERMISSION_CHANGE',
    ACCOUNT_PASSWORD_CHANGE = 'ACCOUNT_PASSWORD_CHANGE',
}

registerEnumType(EventType, { name: 'EventType' });
